### ISSUE TITLE
FileNotFoundError error when trying to execute using docker

### ISSUE THREAD

**Issue by vijayendra-g** [HelenGuohx/logbert#10]
The script run_logbert_hdfs.sh looks for 

train_vocab: /root/.output/hdfs/train
vocab_path: /root/.output/hdfs/vocab.pkl
model_path: /root/.output/hdfs/logbert_mask_ratio_0.65_num_candidate_6/best_model.pth

These are not found.

root@7a564a5a1a6e:/workspace/logbert/scripts# sh run_logbert_hdfs.sh
tee: /root/.logs/hdfs_logbert_mask_ratio_0.65_num_candidate_6.log: No such file or directory
Save options parameters
Traceback (most recent call last):
  File "../main_logbert.py", line 102, in <module>
    main()
  File "../main_logbert.py", line 89, in main
    with open(options["train_vocab"], "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.output/hdfs/train'

**Comment by HelenGuohx** [comment]
Please try to process data before run models ```sh process_bgl.sh```
