### ISSUE TITLE
Come up with data augmentation

### ISSUE THREAD

**Issue by ChangNamAn** [HelenGuohx/logbert#11]
I added the code snippet below for this at split_train_test().
To get more flexibility, I think 2 can change as a variable.

        if data_aug:
            print('Started Data augmentation...')
            window_df_aug = window.generate_sequence(df[["timestamp", "Label", "EventId", "deltaT"]],
                                                window_size=float(window_size) * 60 * 2,
                                                step_size=float(step_size) * 60 * 2
                                                )
            window_df = pd.concat([window_df, window_df_aug]

**Comment by HelenGuohx** [comment]
Yeah, you can definitely modify the code
