### ISSUE TITLE
Can't find Requirement.txt

### ISSUE THREAD

**Issue by fajim1** [HelenGuohx/logbert#15]
Can you point me towards where Requirement.txt is located?

**Comment by hilahersz** [comment]
It looks like it's missing in the project, I saw they have a pipfile instead of requirements (to work with pipenv), however it's empty.

**Comment by hilahersz** [comment]
It looks like it's missing in the project, I saw they have a pipfile instead of requirements (to work with pipenv), however it's empty.

**Comment by HelenGuohx** [comment]
Thanks to [jesama](https://github.com/HelenGuohx/logbert/commits?author=jesama) who helped with the requirement file. see https://github.com/HelenGuohx/logbert/tree/main/environment
