### ISSUE TITLE
cannot find hdfs_sequence.csv

### ISSUE THREAD

**Issue by zora-triumph** [HelenGuohx/logbert#16]
when I excuse  data_process.py, I got error.
FileNotFoundError: [Errno 2] No such file or directory: '../output/hdfs/hdfs_sequence.csv'.

looking forward to your reply!

**Comment by girishl** [comment]
even we are trying to execute data_process.py and getting the same error. File not found.

Kindly share hdfs_sequence.csv file

**Comment by RohitRathore1** [comment]
@zora-triumph Please can you provide `hdfs_sequence.csv` file? We are waiting for your response.
Thanks!

**Comment by HelenGuohx** [comment]
uncomment the code in logbert/HDFS/data_process.py / to generate hdfs_sequence.csv

```
    #parser(input_dir, output_dir, log_file, log_format, 'drain')
    #mapping()
    #hdfs_sampling(log_structured_file)
    generate_train_test(log_sequence_file, n=4855)

```

to be 
```

```
    parser(input_dir, output_dir, log_file, log_format, 'drain')
    mapping()
    hdfs_sampling(log_structured_file)
    generate_train_test(log_sequence_file, n=4855)

```
```

**Comment by RohitRathore1** [comment]
Thanks @HelenGuohx . That was our fault, commented code was already there. We did not read code properly.
