### ISSUE TITLE
您好，抱歉打扰~

### ISSUE THREAD

**Issue by rouse666** [HelenGuohx/logbert#17]
您好，抱歉打扰，想问您下，我按照logbert里的hdfs跑的baseline，有些问题，您的baseline数据是什么格式的呀~方便分享下嘛 , guofangrui@mail.nankai.edu.cn

**Comment by HelenGuohx** [comment]
从text -> train, text split 后的 log sequence 1 2 1 1 1 2 这种。 我找找
