### ISSUE TITLE
关于logdeep中的semantics特征

### ISSUE THREAD

**Issue by nelcon** [HelenGuohx/logbert#21]
作者你好，我在logdeep的代码实验中有看到关于semantics的特征构造相关代码（注释掉了没被使用），其中有个event2semantic_vec.json文件，请问这个文件我有办法获取吗，请问您是把event embedding成了一维向量吗？

**Comment by HelenGuohx** [comment]
你好，抱歉我没有提取log的semantics信息构造event embedding. 你可以参考(Robust log-based anomaly detection on unstable log data)[https://dl.acm.org/doi/10.1145/3338906.3338931]这篇论文关于构造semantic vector. 我是利用神经网络训练出的embedding vector
