### ISSUE TITLE
LAnoBERT : System Log Anomaly Detection based on BERT Masked Language Model

### ISSUE THREAD

**Issue by HC-Guo** [HelenGuohx/logbert#23]
LAnoBERT : System Log Anomaly Detection based on BERT Masked Language Model, almost the same method, why we gain different scores on the same dataset

**Comment by HelenGuohx** [comment]
There are two big differences between LogBERT and LAnoBERT
1) The objective functions.  
2) The calculation of anomaly scores.

**Comment by lianzhaoy** [comment]
@HelenGuohx Are the two inputs also inconsistent?
