### ISSUE TITLE
best_center.pt not found

### ISSUE THREAD

**Issue by shoaib-intro** [HelenGuohx/logbert#32]
I trained model but when predict it ask this file which is not available after training `torch.load(self.model_dir + "best_center.pt")` 
Where to find this file which contains distance and radius?

**Comment by jkennedyvz** [comment]
Ran into the same issue, not sure what generates best_center.pt, but it appears to be a serialized hyperlog checkpoint. If you disable hyperlog then you don't need the file.

`options["hypersphere_loss"] = False`

**Comment by shoaib-intro** [comment]
> 
Generally, it calculates `hypersphere_loss` after at least 10 iterations you can update it or train model for at least 10 iterations to get `best_center.pt`
