### ISSUE TITLE
Results are far from the values reported in the paper

### ISSUE THREAD

**Issue by luisfredgs** [HelenGuohx/logbert#9]
My results are far from the values reported in the paper. For example, after running the code on the BGL dataset I've gotten:

Precision: 88.93%, Recall: 79.86%, F1-measure: 84.15%

Running on HDFS, I've gotten:

Precision: 4.67%, Recall: 79.67%, F1-measure: 8.83%

What happening?  Is there anything I missed?

**Comment by ChangNamAn** [comment]
My results with default parameter are:
BGL 2K
TP: 57, TN: 602, FP: 86, FN: 20
Precision: 39.86%, Recall: 74.03%, F1-measure: 51.82%

HDFS
TP: 6600, TN: 0, FP: 0, FN: 4047
Precision: 100.00%, Recall: 61.99%, F1-measure: 76.54%

**Comment by HelenGuohx** [comment]
Sorry about that, I am checking the code. this is not the original code. this is a modified code

**Comment by ChangNamAn** [comment]
I got the result with custom log data as below.
Precision: 53.81%, Recall: 98.82%, F1-measure: 69.68%

**Comment by HelenGuohx** [comment]
I uploaded an older version of code.

**Comment by AvaIon** [comment]
@ChangNamAn I'm a beginner recently exploring deep learning for log anomaly detection. May I ask if you could provide template code for custom log detection?

**Comment by WenTesla** [comment]
> 我是一名初学者，最近正在探索深度学习以检测日志异常。请问是否可以提供自定义日志检测的模板代码？

使用Drain3 解析模板试试
